//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stilizasia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public Hotel()
        {
            this.Hotel_comment = new HashSet<Hotel_comment>();
            this.HotellImage = new HashSet<HotellImage>();
        }
    
        public int id { get; set; }
        public string Name_hotel { get; set; }
        public Nullable<int> Count_of_stars { get; set; }
        public int Country_code { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<Hotel_comment> Hotel_comment { get; set; }
        public virtual ICollection<HotellImage> HotellImage { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
