//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stilizasia
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotellImage
    {
        public int id { get; set; }
        public int Hotel_id { get; set; }
        public string Image_Source { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
